name: Deploy Frontend

on:
    push:
        branches:
            - main

env:
    PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
    GKE_CLUSTER_NAME: fms-frontend-cluster
    GKE_ZONE: asia-east1

    DOCKERHUB_USERNAME: sechmachine
    IMAGE_TAG: ${{ github.sha }}

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ env.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }} # Add DOCKERHUB_PASSWORD secret

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: ${{ env.DOCKERHUB_USERNAME }}/frontend:latest

            - id: 'auth'
              uses: 'google-github-actions/auth@v2'
              with:
                  credentials_json: '${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}'


            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v2
              with:
                  project_id: ${{ env.PROJECT_ID }}


            - name: Get GKE credentials
              uses: google-github-actions/get-gke-credentials@v2
              with:
                  cluster_name: ${{ env.GKE_CLUSTER_NAME }}
                  location: ${{ env.GKE_ZONE }}

            - name: Deploy to Kubernetes
              run: |
                  kubectl apply -f deployment.yaml
                  kubectl rollout restart deployment/frontend-deployment
